// Generated by `npm run gen:types`. Run after the backend is up.
// This stub exists so the project compiles before the first generation.
export interface paths {}
export interface components {
  schemas: Record<string, never>;
}
